apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fast
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.175.5.229:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: k8s
  userId: admin
  usersecretName: ceph-secret-admin
  fsType: ext4